Build/urls.py
from django.urls import path
from . import views
from .views import *


urlpatterns = [
    path('', HomePage.as_view(), name='homepage'),
    path('accessories/', List_accessories.as_view(), name='accessories'),
    path('buildspc/', BuildsPC.as_view(), name='buildspc'),
    path('computer/<slug:slug>/', ComputerDetail.as_view(), name='computer'),
    path('<str:component_type>/<int:pk>/', ComponentDetailView.as_view(), name='component_detail'),
    path('category/<slug:slug>/', CategoryItemsView.as_view(), name='category-items'),
    # path('configuratepc/', PCConfigurateView.as_view(), name='configuratepc'),
    path('buildspcusers/', BuildPCUsers.as_view(), name='buildpcusers'),
    path('configurator/add/<str:category>/<int:pk>/', add_to_configurator, name='add_to_configurator'),
    path('configurator/', current_configurator, name='current_configurator'),
    path('configurator/save/', save_configurator, name='save_configurator'),
    path('configurator/items/<str:category>/', CategoryItemsView.as_view(), name='list_items'),
    path('comparison/add/<str:category>/<int:pk>/', add_to_comparison, name='add_to_comparison'),
    path('comparison/', comparison, name='comparison'),
    path('comparison/remove/<str:category>/<int:pk>/', remove_from_comparison, name='remove_from_comparison'),
    # path('price/', price_view, name='price-view'),
]

BuildPC/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Build.views import *
from BuildPC import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Build.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path

from users.views import LoginUser, logout_view, RegisterUser, ProfileUsers, ChangePassword

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
    path('password-change/', ChangePassword.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('profile/', ProfileUsers.as_view(), name='profile'),
]

users/forms.py
from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Имя пользователя')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Пароль')
    captcha = CaptchaField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', )
        labels = {
            'username': 'Никнейм',
            'email': 'E-Mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'password1': 'Пароль',
            'password2': 'Повторите пароль',
        }

    def clean_password(self):
            cd = self.cleaned_data
            if cd['password1'] != cd['password2']:
                raise forms.ValidationError('Пароли не совпадают!')
            return cd['password1']

    def clean_email(self):
            email = self.cleaned_data['email']
            if get_user_model().objects .filter(email=email).exists():
                raise forms.ValidationError('Пользователь с таким Email адресом уже существует')
            return email


class ProfileForm(forms.ModelForm):
    username = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(disabled=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')
        labels = {
            'email': 'E-Mail',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }


class UserChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

users/views.py
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView

from Build.models import Computer
from users.forms import LoginUserForm, RegisterUserForm, ProfileForm, UserChangePasswordForm

app_name = 'users'

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse_lazy('homepage')

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('homepage'))

class ProfileUsers(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileForm
    template_name = 'users/profile.html'

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['computer'] = self.request.user.author.all()
        return context

class ChangePassword(PasswordChangeView):
    form_class = UserChangePasswordForm
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:password_change_done')

users/templates/users/build_pc.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <main class='main'>
        <div class="main-background-users">
            <img src="{% static 'users/image/main-users.jpg' %}" alt="main photo">
        </div>
        <div class="auth-container">
            <div class="auth">
                <h1 class="auth-h1">Профиль пользователя</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                        <p class=""><label class="form-label-auth" for="{{ for.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                        <div class="form-error">{{ f.error }}</div>
                    {% endfor %}
                    <p>
                        <button type="submit">Изменить</button>
                    </p>
                    <p>
                    <h1 class="auth-h1"><a href="{% url 'users:password_change' %}">Изменить пароль</a></h1>
                    </p>
                    <h1 class="auth-h1"></h1>
                    <a class="auth-h1" href="#">Посмотреть все свои сборки</a>
                </form>
            </div>
        </div>
        </section>
    </main>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='main'>
        <div class="main-background-users">
            <img src="{% static 'users/image/main-users.jpg' %}" alt="main photo">
        </div>
        <div class="auth-container">
            <div class="auth">
                <h1 class="auth-h1">Авторизация</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                        {% if f.name != 'captcha' %}
                        <p class=""><label class="form-label-auth" for="{{ for.id_for_label }}">{{ f.label }}</label>{{ f }}
                        </p>
                        <div class="form-error">{{ f.error }}</div>
                        {% endif %}
                    {% endfor %}
                    <div class="captcha">
                        {{ form.captcha }}
                    </div>
                    <p>
                        <button type="submit">Войти</button>
                    </p>
                </form>

                <div class="register-container">
                    <a href="#" class="password-recovery">Забыли пароль?</a>
                    <a href="{% url 'users:register' %}" class="register">Зарегистрироваться</a>
                </div>
            </div>
        </div>
        </section>
    </main>
{% endblock %}

users/templates/users/password_change.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='main'>
        <div class="main-background-users">
            <img src="{% static 'users/image/main-users.jpg' %}" alt="main photo">
        </div>
        <div class="auth-container">
            <div class="auth">
                <h1 class="auth-h1">Изменение пароля</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                        <p class=""><label class="form-label-auth" for="{{ for.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                        <div class="form-error">{{ f.error }}</div>
                    {% endfor %}
                    <p>
                        <button type="submit">Изменить</button>
                    </p>
                </form>
            </div>
        </div>
        </section>
    </main>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='main'>
        <div class="main-background-users">
            <img src="{% static 'users/image/main-users.jpg' %}" alt="main photo">
        </div>
        <div class="auth-container">
            <div class="auth">
                <h1 class="auth-h1">Пароль успешно изменён!</h1>
                <h1 class="auth-h1"><a href="{% url 'users:profile' %}">Вернуться в профиль</a></h1>
            </div>
        </div>
        </section>
    </main>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <main class='main'>
        <div class="main-background-users">
            <img src="{% static 'users/image/main-users.jpg' %}" alt="main photo">
        </div>
        <div class="auth-container">
            <div class="profile-container">
                <div class="auth">
                    <h1 class="auth-h1">Профиль пользователя</h1>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                            <p class=""><label class="form-label-auth"
                                               for="{{ for.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                            <div class="form-error">{{ f.error }}</div>
                        {% endfor %}
                        <p>
                            <button type="submit">Изменить</button>
                        </p>
                        <p>
                        <h1 class="auth-h1"><a href="{% url 'users:password_change' %}">Изменить пароль</a></h1>
                        </p>
                                    </form>
                    </div>
                <div class="user-builds">
                    <h1 class="auth-h1">Сборки которые вы создавали:</h1>
                    {% for c in computer %}
                        <a class="build-url-user" href="{% url 'computer' c.slug %}">Название: {{ c.name }} | {{ c.gpu.name }} | {{ c.cpu.name }}</a>
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
        </section>
    </main>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='main'>
        <div class="main-background-users">
            <img src="{% static 'users/image/main-users.jpg' %}" alt="main photo">
        </div>
        <div class="auth-container">
            <div class="auth">
                <h1 class="auth-h1">Регистрация</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                        {% if f.name != 'captcha' %}
                        <p class=""><label class="form-label-auth" for="{{ for.id_for_label }}">{{ f.label }}</label>{{ f }}
                        </p>
                        <div class="form-error">{{ f.error }}</div>
                        {% endif %}
                    {% endfor %}
                    <div class="captcha">
                        {{ form.captcha }}
                    </div>

                    <p>
                        <button type="submit">Зарегистрироваться</button>
                    </p>
                </form>
            </div>
        </div>
        </section>
    </main>
{% endblock %}